src/main/java/controller/CSCenterController.java
src/main/webapp/cscenter/csmain.jsp
src/main/webapp/index.jsp

CsCenter Added Index Modified

---

src/main/webapp/cscenter/csmain.jsp
src/main/webapp/index.jsp

index cscenter modified

---

src/main/webapp/cscenter/csmain.jsp

Csmain.jsp Modified

---

src/main/webapp/index.jsp

index.jsp modified

---

src/main/java/controller/MemberController.java
src/main/java/dao/MemberDAO.java
src/main/webapp/member/mypage.jsp

mypage.jsp 추가

---

src/main/java/utils/SendMail.java
src/main/webapp/cscenter/csemail.jsp
src/main/webapp/cscenter/csmain.jsp

csemail.jsp added
csmain.jps modified
sendmail.java class added

CSEMAIL ADDED

---

src/main/webapp/member/mypage.jsp

mypage modified

---

src/main/java/controller/CSCenterController.java
src/main/java/dao/MemberDAO.java

csemail added
searchemail added

CSController and MemberDAO modified

---

src/main/webapp/cscenter/csemail.jsp
src/main/webapp/cscenter/csmain.jsp

Csmain.jsp Tapform change and Csemail.jsp Modified

---

src/main/java/utils/SendMail.java

sendmail modified

---

src/main/java/controller/AdminController.java
src/main/java/dao/MemberDAO.java
src/main/java/utils/SendMail.java
src/main/webapp/admin/detailViewMember.jsp

자잘한 수정과 샌드메일 비번변경
디테일뷰 페이지 추가요~~

detailMember Added and admin mdao modified

---

src/main/java/controller/AdminController.java
src/main/java/dao/MemberDAO.java
src/main/webapp/admin/adminPwCheck.jsp
src/main/webapp/admin/adminmain.jsp
src/main/webapp/admin/banishMember.jsp
src/main/webapp/admin/detailViewMember.jsp
src/main/webapp/index.jsp

AdminBanMember Added

---

src/main/java/controller/AdminController.java
src/main/java/dao/AdminDAO.java
src/main/webapp/admin/adminBoard1List.jsp
src/main/webapp/admin/adminBoard2List.jsp
src/main/webapp/admin/adminReply1List.jsp
src/main/webapp/admin/adminReply2List.jsp
src/main/webapp/admin/adminmain.jsp
src/main/webapp/admin/detailViewMember.jsp
src/main/webapp/cscenter/csmain.jsp

Board Reply Added 

---

src/main/webapp/admin/adminReply2List.jsp
src/main/webapp/board2/board2_DetailView.jsp

Brd2 DetailView Reply Modified

---

src/main/java/controller/AdminController.java
src/main/java/dao/AdminDAO.java
src/main/webapp/admin/adminReply1List.jsp
src/main/webapp/admin/adminReply2List.jsp
src/main/webapp/admin/adminmain.jsp
src/main/webapp/css/admin/adminmain.css

Admin BrdSearch Added

---

src/main/webapp/board2/board2_List.jsp
src/main/webapp/board2/board2_Write.jsp
src/main/webapp/css/board2/board2_Write.css

board2 css modifyed

---

src/main/webapp/board2/board2_Write.jsp

board2write css

---

src/main/webapp/admin/adminReply1List.jsp

AdminList Modified

---

src/main/java/dao/AdminDAO.java
src/main/webapp/admin/adminBoard1List.jsp
src/main/webapp/admin/adminBoard2List.jsp
src/main/webapp/admin/adminmain.jsp
src/main/webapp/admin/detailViewMember.jsp
src/main/webapp/css/admin/adminBoard1List.css
src/main/webapp/css/admin/adminBoard2List.css
src/main/webapp/css/admin/adminmain.css
src/main/webapp/css/admin/adminmemberpage.css

Admin Brdlist Css Modified

---

src/main/java/controller/MemberController.java
src/main/java/dao/MemberDAO.java
src/main/webapp/board2/board2_DetailView.jsp
src/main/webapp/css/member/mypage.css
src/main/webapp/member/findid.jsp
src/main/webapp/member/findpw.jsp
src/main/webapp/member/memberout.jsp
src/main/webapp/member/modifiypw.jsp
src/main/webapp/member/mypage.jsp

1. 아이디 찾기에 카카오 회원 추가
2. detailview 이미지 적용
3. 팝업창 css추가

변경사항 pull request

---

src/main/java/controller/AdminController.java
src/main/java/dao/AdminDAO.java
src/main/webapp/admin/adminBoard1List.jsp
src/main/webapp/admin/adminBoard2List.jsp
src/main/webapp/admin/adminReply1List.jsp
src/main/webapp/admin/adminReply2List.jsp
src/main/webapp/admin/adminmain.jsp
src/main/webapp/cscenter/csemail.jsp
src/main/webapp/cscenter/csmain.jsp
src/main/webapp/css/admin/adminBoard1List.css
src/main/webapp/css/admin/adminmain.css

Admin MemberSearch & CSS Modified

---

src/main/webapp/index.jsp
src/main/webapp/member/findid.jsp
src/main/webapp/member/findpw.jsp
src/main/webapp/member/modifiypw.jsp

카카오 아이디 비밀번호 찾기 추가
비밀번호 변경 버그 해결

css modifyed

---

src/main/webapp/admin/adminReply2List.jsp

Admin Reply2List Modified

---

src/main/webapp/cscenter/csmain.jsp

Admin Linked

---

src/main/webapp/admin/adminBoard1List.jsp
src/main/webapp/admin/adminBoard2List.jsp
src/main/webapp/admin/adminModifyMember.jsp
src/main/webapp/admin/adminReply1List.jsp
src/main/webapp/admin/adminReply2List.jsp
src/main/webapp/admin/adminmain.jsp
src/main/webapp/admin/banishMember.jsp
src/main/webapp/admin/detailViewMember.jsp
src/main/webapp/board1/board1_DetailView.jsp
src/main/webapp/board1/board1_List.jsp
src/main/webapp/board1/board1_Modify.jsp
src/main/webapp/board1/board1_Write.jsp
src/main/webapp/board2/board2_DetailView.jsp
src/main/webapp/board2/board2_List.jsp
src/main/webapp/board2/board2_Write.jsp
src/main/webapp/cscenter/csemail.jsp
src/main/webapp/cscenter/csmain.jsp
src/main/webapp/cscenter/csmap.jsp
src/main/webapp/index.jsp
src/main/webapp/member/joinform.jsp
src/main/webapp/member/myReply.jsp
src/main/webapp/member/myWriting.jsp
src/main/webapp/member/mypage.jsp

Footer Linked Change

---

src/main/webapp/cscenter/csmain.jsp
src/main/webapp/cscenter/csmap.jsp
src/main/webapp/css/cscenter/csmain.css

CSCenter CSmap Css Modified

---

src/main/webapp/admin/adminModifyMember.jsp
src/main/webapp/admin/detailViewMember.jsp
src/main/webapp/cscenter/csemail.jsp
src/main/webapp/cscenter/csmain.jsp

admin Test Modified

---

src/main/webapp/board1/board1_DetailView.jsp
src/main/webapp/index.jsp
src/main/webapp/member/findpw.jsp
src/main/webapp/member/mypage.jsp

Mypage btn display none modified

---

src/main/webapp/error.html

error MSG Added

---

src/main/webapp/error.html

error.hrml modifyed

---

src/main/webapp/cscenter/csnotice.jsp
src/main/webapp/cscenter/detailNotice.jsp
src/main/webapp/cscenter/writeNotice.jsp
src/main/webapp/css/cscenter/csnotice.css
src/main/webapp/css/cscenter/csnoticeWrite.css

CSNotice CSS Added

---

src/main/webapp/board1/popup03.jsp

Popup 1 button modified

---

src/main/webapp/admin/adminReply1List.jsp
src/main/webapp/css/admin/adminReply1List.css

reply modified
